server:
  port: 9001

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: service1
          uri: http://service1.taskoo.net
          predicates:
            - Path=/services/**
        - id: service31
          uri: http://client.taskoo.net
          predicates:
            - Path=/client/**
        - id: gateway
          uri: http://gateway.taskoo.net
          predicates:
            - Path=/gateway/**

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true # 유레카 서비스에 (자신을) 등록 여부
    fetch-registry: true
    serviceUrl:
      defaultZone: http://eureka.taskoo.net/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"
